# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/


build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script: 
  #   - apt update && apt -y install make autoconf 
  script: 
    - mkdir .build
    - x86_64-w64-mingw32-gcc Proyecto\ final/main.c -lwinmm -o .build/juego.exe
    - ls
    - cp -r sounds .build
    - zip -r /var/www/html/juego/juego.zip .build
  artifacts:
    paths:
      - /var/www/html/juego/juego.exe
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"


